default:
  image: python:3.12-bookworm
  before_script:
    - curl -sSL https://install.python-poetry.org | python3 - --git https://github.com/python-poetry/poetry.git@main
    - export PATH="$HOME/.local/bin:$PATH"
    - poetry install

stages:
  - tests
  - lint


MyPy:
  stage: lint
  script:
    - poetry run mypy --config-file setup.cfg

Linter:
  stage: lint
  script:
    - poetry run flake8 --config setup.cfg src/app

Tests:
  stage: tests
  script:
    - echo "$PWD"
    - export PYTHONPATH="$PWD/src"
    - poetry run pytest src
  artifacts:
        name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
        paths:
            - coverage/
        when: on_success
        expire_in: 1 week
  coverage: '/TOTAL.*\s+(\d+%)$/'

