"""initial

Revision ID: 78680546e088
Revises: 
Create Date: 2024-08-20 19:28:24.129964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78680546e088'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=320), nullable=False),
    sa.Column('password', sa.String(length=1024), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('balance', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='auth_schema'
    )
    op.create_index(op.f('ix_auth_schema_users_login'), 'users', ['login'], unique=True, schema='auth_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_schema_users_login'), table_name='users', schema='auth_schema')
    op.drop_table('users', schema='auth_schema')
    # ### end Alembic commands ###
