"""empty message

Revision ID: 9652267bfebf
Revises: 894dc483bbb9
Create Date: 2024-08-21 06:21:51.377006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9652267bfebf'
down_revision: Union[str, None] = '894dc483bbb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('transaction_type', sa.Enum('deposit', 'withdrawal',
                                                          name='transactiontype'), nullable=False),
                    sa.Column('transaction_sum', sa.BigInteger(), nullable=False),
                    sa.Column('creation_time', sa.DateTime(timezone=True),
                              server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['auth_schema.users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='transaction_schema'
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions', schema='transaction_schema')
    # ### end Alembic commands ###
