apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "transaction-service-pompeeva.fullname" . }}
  labels:
    {{- include "transaction-service-pompeeva.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "transaction-service-pompeeva.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "transaction-service-pompeeva.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
          - name: DB_HOST_POMPEEVA
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}
                key: db_host
          - name: DB_PORT_POMPEEVA
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}
                key: db_port
          - name: DB_NAME_POMPEEVA
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}
                key: db_name
          - name: DB_USER_POMPEEVA
            valueFrom:
              secretKeyRef:
                name: transaction-service-pompeeva-secret
                key: db_user
          - name: DB_PASS_POMPEEVA
            valueFrom:
              secretKeyRef:
                name: transaction-service-pompeeva-secret
                key: db_pass
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
